//! Fixed P-384 known-answer fixtures generated by PyCA (tests/interop/p384_reference.py),
//! not by IPG or IronCrypto. All scalars in these fixtures are public test data.
//!
//! IPG has no software P-384 secret format; `FixtureToken` stands in for a PKCS#11
//! token through the public provider interface, exactly as the hardware backend does.
use ic_core::traits::{KeyAgreement, SignatureScheme};
use ic_ec::{EcdhP384, EcdsaP384Sha384};
use ipg_json::Value;
use ipg_json::de::DeserializeOwned;
use iron_privacy_guard::secrets::Zeroizing;
use iron_privacy_guard::{
    artifact,
    crypto::{self, Custody, Envelope, IdentityKey, PublicKey, Signature},
    lifecycle::{self, Revocation, RevocationReason, Validity},
    trust::TrustStore,
};

fn fixture() -> Value {
    ipg_json::from_str(include_str!("vectors/native-p384-v1.json")).unwrap()
}
fn decode<T: DeserializeOwned>(value: &Value) -> T {
    ipg_json::from_value(value.clone()).unwrap()
}
fn bytes(value: &Value) -> Vec<u8> {
    iron_privacy_guard::hex::decode(value.as_str().unwrap()).unwrap()
}

struct FixtureToken {
    public: PublicKey,
    encryption: Vec<u8>,
    signing: Vec<u8>,
}
impl FixtureToken {
    fn new(v: &Value) -> Self {
        Self {
            public: decode(&v["public"]),
            encryption: bytes(&v["encryption_scalar_hex"]),
            signing: bytes(&v["signing_scalar_hex"]),
        }
    }
}
impl IdentityKey for FixtureToken {
    fn public(&self) -> &PublicKey {
        &self.public
    }
    fn custody(&self) -> Custody {
        Custody::Hardware
    }
    fn sign_raw(&self, message: &[u8]) -> iron_privacy_guard::error::Result<Vec<u8>> {
        let mut signature = vec![0; 96];
        EcdsaP384Sha384::sign(&self.signing, message, &mut signature)?;
        Ok(signature)
    }
    fn agree(&self, peer: &[u8]) -> iron_privacy_guard::error::Result<Zeroizing<Vec<u8>>> {
        let mut shared = Zeroizing::new(vec![0; 48]);
        EcdhP384::agree(&self.encryption, peer, &mut shared)?;
        Ok(shared)
    }
}

fn framed(domain: &str, fields: &[&[u8]]) -> Vec<u8> {
    let mut out = domain.as_bytes().to_vec();
    for field in fields {
        out.extend_from_slice(&(field.len() as u64).to_be_bytes());
        out.extend_from_slice(field);
    }
    out
}

#[test]
fn independent_p384_identity_derives_the_same_fingerprint() {
    let v = fixture();
    let token = FixtureToken::new(&v);
    let (mut encryption, mut signing) = ([0; 97], [0; 97]);
    EcdhP384::public_key(&token.encryption, &mut encryption).unwrap();
    EcdsaP384Sha384::public_key(&token.signing, &mut signing).unwrap();
    let derived = crypto::identity(crypto::Suite::P384, &encryption, &signing).unwrap();
    assert_eq!(derived, token.public);
    let metadata = artifact::inspect(&ipg_json::to_vec(&v["public"]).unwrap()).unwrap();
    assert_eq!(metadata.format, crypto::P384_KEY_FORMAT);
    assert_eq!(metadata.fingerprint.unwrap(), token.public.fingerprint);
}

#[test]
fn independent_p384_envelopes_decrypt_with_matching_intermediates() {
    use ic_core::traits::Digest;
    use ic_hash::Sha384;
    let v = fixture();
    let token = FixtureToken::new(&v);
    for item in v["messages"].as_array().unwrap() {
        let envelope: Envelope = decode(&item["envelope"]);
        envelope.validate().unwrap();
        let trace = &item["encryption_trace"];
        let shared = token
            .agree(&bytes(&item["envelope"]["ephemeral_key"]))
            .unwrap();
        assert_eq!(*shared, bytes(&trace["shared_secret_hex"]));
        // ANSI X9.63 KDF, one SHA-384 block: SHA-384(Z || 00000001 || SHA-384(AAD)).
        let shared_info = Sha384::digest(&bytes(&trace["aad_hex"]));
        let block = Sha384::digest(&[&shared[..], &[0, 0, 0, 1], shared_info.as_ref()].concat());
        assert_eq!(
            block.as_ref()[..32].to_vec(),
            bytes(&trace["derived_key_hex"])
        );
        assert_eq!(
            crypto::x963_kdf_sha384(&shared, shared_info.as_ref()).to_vec(),
            bytes(&trace["derived_key_hex"])
        );
        assert_eq!(
            *crypto::decrypt_with(&token, &envelope).unwrap(),
            bytes(&item["message_hex"])
        );
        for field in ["tag", "nonce", "ciphertext", "ephemeral_key", "recipient"] {
            let mut tampered = item["envelope"].clone();
            let mut decoded = bytes(&tampered[field]);
            if decoded.is_empty() {
                continue;
            }
            // Flip a coordinate bit, not the SEC1 prefix, so points stay well-formed text.
            let index = decoded.len() - 1;
            decoded[index] ^= 1;
            tampered[field] = Value::String(iron_privacy_guard::hex::encode(decoded));
            let tampered: Envelope = decode(&tampered);
            assert!(crypto::decrypt_with(&token, &tampered).is_err(), "{field}");
        }
    }
}

#[test]
fn independent_p384_signatures_verify_and_reproduce_rfc6979_bytes() {
    let v = fixture();
    let token = FixtureToken::new(&v);
    let public = &token.public;
    for item in v["messages"].as_array().unwrap() {
        let message = bytes(&item["message_hex"]);
        let signature: Signature = decode(&item["signature"]);
        crypto::verify(public, &public.fingerprint, &signature, &message).unwrap();
        // IronCrypto and PyCA both implement deterministic RFC 6979 nonces.
        let reproduced = crypto::sign_with(&token, &message).unwrap();
        assert_eq!(reproduced.signature, signature.signature);
        let mut altered = message.clone();
        altered.push(0);
        assert!(crypto::verify(public, &public.fingerprint, &signature, &altered).is_err());
        let digest = framed(
            "IPG detached signature v1 ecdsa-p384-sha384",
            &[public.fingerprint.as_bytes(), &message],
        );
        EcdsaP384Sha384::verify(
            &public.signing_key_bytes().unwrap(),
            &digest,
            &bytes(&item["signature"]["signature"]),
        )
        .unwrap();
    }
}

#[test]
fn independent_p384_certificates_and_snapshots_match() {
    let v = fixture();
    let token = FixtureToken::new(&v);
    let fingerprint = token.public.fingerprint.clone();
    for (value, reason) in v["revocations"].as_array().unwrap().iter().zip([
        RevocationReason::Compromised,
        RevocationReason::Superseded,
        RevocationReason::Retired,
    ]) {
        let revocation: Revocation = decode(value);
        lifecycle::verify_revocation(&token.public, &fingerprint, &revocation).unwrap();
        let reproduced = lifecycle::revoke_with(&token, &fingerprint, reason).unwrap();
        assert_eq!(ipg_json::to_value(reproduced).unwrap(), *value);
    }
    let validity: Validity = decode(&v["validity"]);
    lifecycle::verify_validity(&token.public, &fingerprint, &validity).unwrap();
    let reproduced = lifecycle::validity_with(
        &token,
        &fingerprint,
        validity.not_before,
        validity.not_after,
    )
    .unwrap();
    assert_eq!(ipg_json::to_value(reproduced).unwrap(), v["validity"]);
    for snapshot in v["snapshots"].as_array().unwrap() {
        let store: TrustStore = decode(&snapshot["snapshot"]);
        assert_eq!(
            store.digest().unwrap(),
            snapshot["digest"].as_str().unwrap()
        );
    }
}

#[test]
fn p384_artifacts_reject_suite_confusion() {
    let v = fixture();
    let token = FixtureToken::new(&v);
    let item = &v["messages"][3];
    let mut envelope = item["envelope"].clone();
    envelope["suite"] = crypto::SUITE.into();
    assert!(decode::<Envelope>(&envelope).validate().is_err());
    let mut signature = item["signature"].clone();
    signature["algorithm"] = "ed25519".into();
    assert!(decode::<Signature>(&signature).validate().is_err());
    let mut public = v["public"].clone();
    public["format"] = crypto::KEY_FORMAT.into();
    assert!(decode::<PublicKey>(&public).validate().is_err());
    // A reference to this identity is public data and inspects without a token.
    let reference = ipg_json::json!({"format":"ipg-pkcs11-key-v1","public":v["public"],
        "token":{"serial":"0123456789abcdef","label":"ipg-test","manufacturer":"Test","model":"Oracle"},
        "encryption_key_id":"01".repeat(16),"signing_key_id":"02".repeat(16)});
    let metadata = artifact::inspect(&ipg_json::to_vec(&reference).unwrap()).unwrap();
    assert_eq!(metadata.fingerprint.unwrap(), token.public.fingerprint);
    let mut same_ids = reference.clone();
    same_ids["signing_key_id"] = same_ids["encryption_key_id"].clone();
    assert!(artifact::inspect(&ipg_json::to_vec(&same_ids).unwrap()).is_err());
    let mut software_identity = reference.clone();
    software_identity["public"] = ipg_json::json!({"format":"ipg-public-v1",
        "encryption_key":"00".repeat(32),"signing_key":"00".repeat(32),"fingerprint":"00".repeat(32)});
    assert!(artifact::inspect(&ipg_json::to_vec(&software_identity).unwrap()).is_err());
}
