//! Fixed known-answer fixtures generated by PyCA, not by IPG or IronCrypto.
//! All key material and passphrases in these fixtures are public test data.
use ipg_json::Value;
use ipg_json::de::DeserializeOwned;
use iron_privacy_guard::{
    crypto::{self, Envelope, PublicKey, SecretKey, Signature},
    lifecycle::{self, Revocation, Validity},
    trust::{Eligibility, TrustStore},
};

fn fixture() -> Value {
    ipg_json::from_str(include_str!("vectors/native-v1.json")).unwrap()
}
fn decode<T: DeserializeOwned>(value: &Value) -> T {
    ipg_json::from_value(value.clone()).unwrap()
}
fn bytes(value: &Value) -> Vec<u8> {
    iron_privacy_guard::hex::decode(value.as_str().unwrap()).unwrap()
}
fn alter_hex(value: &mut Value) {
    let mut decoded = bytes(value);
    decoded[0] ^= 1;
    *value = Value::String(iron_privacy_guard::hex::encode(decoded));
}

#[test]
fn independent_protected_identity_and_argon2_vector() {
    use ic_kdf::{Argon2Params, Variant, argon2};
    let v = fixture();
    let secret: SecretKey = decode(&v["secret"]);
    let password = bytes(&v["password_hex"]);
    let seeds = crypto::unlock(&secret, &password).unwrap();
    assert_eq!(seeds.as_slice(), bytes(&v["seeds_hex"]));
    let public: PublicKey = decode(&v["public"]);
    public.validate().unwrap();
    assert_eq!(secret.public.fingerprint, public.fingerprint);
    let mut derived = [0; 32];
    argon2(
        Variant::Argon2id,
        &Argon2Params::INTERACTIVE,
        &password,
        &bytes(&v["secret"]["salt"]),
        &mut derived,
    )
    .unwrap();
    assert_eq!(
        derived.as_slice(),
        bytes(&v["secret_trace"]["derived_key_hex"])
    );
}

#[test]
fn independent_envelopes_cover_empty_and_block_boundaries() {
    use ic_core::traits::{Kdf, KeyAgreement};
    use ic_ec::X25519;
    use ic_kdf::Hkdf;
    use ic_mac::HmacSha256;
    let v = fixture();
    let secret: SecretKey = decode(&v["secret"]);
    let password = bytes(&v["password_hex"]);
    for message in v["messages"].as_array().unwrap() {
        let envelope: Envelope = decode(&message["envelope"]);
        assert_eq!(
            *crypto::decrypt(&secret, &password, &envelope).unwrap(),
            bytes(&message["plaintext_hex"]),
            "{}",
            message["name"]
        );
        let mut shared = [0; 32];
        X25519::agree(
            &bytes(&message["ephemeral_seed_hex"]),
            &bytes(&v["public"]["encryption_key"]),
            &mut shared,
        )
        .unwrap();
        assert_eq!(
            shared.as_slice(),
            bytes(&message["encryption_trace"]["shared_secret_hex"])
        );
        let mut derived = [0; 32];
        Hkdf::<HmacSha256>::derive(
            &shared,
            b"IPG encryption v1",
            &bytes(&message["encryption_trace"]["aad_hex"]),
            &mut derived,
        )
        .unwrap();
        assert_eq!(
            derived.as_slice(),
            bytes(&message["encryption_trace"]["derived_key_hex"])
        );
    }
}

#[test]
fn independent_signatures_and_lifecycle_certificates_are_exact() {
    let v = fixture();
    let secret: SecretKey = decode(&v["secret"]);
    let public = &secret.public;
    let password = bytes(&v["password_hex"]);
    for message in v["messages"].as_array().unwrap() {
        let signature: Signature = decode(&message["signature"]);
        let plaintext = bytes(&message["plaintext_hex"]);
        crypto::verify(public, &public.fingerprint, &signature, &plaintext).unwrap();
        let generated = crypto::sign(&secret, &password, &plaintext).unwrap();
        assert_eq!(ipg_json::to_value(generated).unwrap(), message["signature"]);
    }
    for value in v["revocations"].as_array().unwrap() {
        let certificate: Revocation = decode(value);
        lifecycle::verify_revocation(public, &public.fingerprint, &certificate).unwrap();
        let generated =
            lifecycle::revoke(&secret, &public.fingerprint, &password, certificate.reason).unwrap();
        assert_eq!(ipg_json::to_value(generated).unwrap(), *value);
    }
    let certificate: Validity = decode(&v["validity"]);
    lifecycle::verify_validity(public, &public.fingerprint, &certificate).unwrap();
    let generated = lifecycle::validity(
        &secret,
        &public.fingerprint,
        &password,
        certificate.not_before,
        certificate.not_after,
    )
    .unwrap();
    assert_eq!(ipg_json::to_value(generated).unwrap(), v["validity"]);
}

#[test]
fn independent_snapshot_commitments_cover_both_versions() {
    let v = fixture();
    for item in v["snapshots"].as_array().unwrap() {
        let store: TrustStore = decode(&item["snapshot"]);
        assert_eq!(store.digest().unwrap(), item["digest"].as_str().unwrap());
        let expected = if store.entries[0].revocation.is_some() {
            Eligibility::Revoked
        } else {
            Eligibility::Permitted
        };
        assert_eq!(
            store
                .evaluate(v["public"]["fingerprint"].as_str().unwrap(), 1800000000)
                .unwrap(),
            expected
        );
    }
}

#[test]
fn modified_independent_vectors_fail_authentication() {
    let v = fixture();
    let secret: SecretKey = decode(&v["secret"]);
    let password = bytes(&v["password_hex"]);
    for field in ["ciphertext", "tag", "nonce", "ephemeral_key"] {
        let mut altered = v["messages"][8]["envelope"].clone();
        alter_hex(&mut altered[field]);
        assert!(
            crypto::decrypt(&secret, &password, &decode(&altered)).is_err(),
            "{field}"
        );
    }
    for field in ["ciphertext", "tag", "nonce", "salt"] {
        let mut altered = v["secret"].clone();
        alter_hex(&mut altered[field]);
        assert!(
            crypto::unlock(&decode(&altered), &password).is_err(),
            "{field}"
        );
    }
    // The binary password contains NUL, non-UTF8 and CRLF; trimming changes it.
    assert!(crypto::unlock(&secret, &password[..password.len() - 2]).is_err());
    let signature: Signature = decode(&v["messages"][8]["signature"]);
    let mut plaintext = bytes(&v["messages"][8]["plaintext_hex"]);
    plaintext[0] ^= 1;
    assert!(
        crypto::verify(
            &secret.public,
            &secret.public.fingerprint,
            &signature,
            &plaintext
        )
        .is_err()
    );
}
