//! apg-public-p384-mldsa65-v1 fixtures generated by PyCA/OpenSSL
//! (tests/interop/p384_mldsa_reference.py), not by APG or IronCrypto. All scalars
//! and seeds are public test data.
//!
//! APG has no software secret format for this suite; `FixtureService` stands in for
//! AWS KMS through the public provider interface, as the KMS backend does.
use ic_core::traits::{KeyAgreement, SignatureScheme};
use ic_ec::{EcdhP384, EcdsaP384Sha384};
use ic_mldsa::sign as mldsa;
use iron_privacy_guardian::{
    artifact,
    crypto::{self, Custody, Envelope, IdentityKey, PublicKey, Signature},
    lifecycle::{self, Revocation, RevocationReason, Validity},
    trust::TrustStore,
};
use serde::de::DeserializeOwned;
use serde_json::Value;
use zeroize::Zeroizing;

fn fixture() -> Value {
    serde_json::from_str(include_str!("vectors/native-p384-mldsa65-v1.json")).unwrap()
}
fn decode<T: DeserializeOwned>(value: &Value) -> T {
    serde_json::from_value(value.clone()).unwrap()
}
fn bytes(value: &Value) -> Vec<u8> {
    hex::decode(value.as_str().unwrap()).unwrap()
}
fn framed(domain: &str, fields: &[&[u8]]) -> Vec<u8> {
    let mut out = domain.as_bytes().to_vec();
    for field in fields {
        out.extend_from_slice(&(field.len() as u64).to_be_bytes());
        out.extend_from_slice(field);
    }
    out
}

struct FixtureService {
    public: PublicKey,
    encryption: Vec<u8>,
    signing: Vec<u8>,
    mldsa_secret: Box<[u8; mldsa::SECRET_KEY_LEN]>,
}
impl FixtureService {
    fn new(v: &Value) -> Self {
        let seed: [u8; 32] = bytes(&v["mldsa_seed_hex"]).try_into().unwrap();
        let mut public = Box::new([0; mldsa::PUBLIC_KEY_LEN]);
        let mut secret = Box::new([0; mldsa::SECRET_KEY_LEN]);
        assert!(mldsa::keygen(&seed, &mut public, &mut secret));
        Self {
            public: decode(&v["public"]),
            encryption: bytes(&v["encryption_scalar_hex"]),
            signing: bytes(&v["signing_scalar_hex"]),
            mldsa_secret: secret,
        }
    }
}
impl IdentityKey for FixtureService {
    fn public(&self) -> &PublicKey {
        &self.public
    }
    fn custody(&self) -> Custody {
        Custody::Service
    }
    fn sign_raw(&self, message: &[u8]) -> iron_privacy_guardian::error::Result<Vec<u8>> {
        let mut signature = vec![0; 96];
        EcdsaP384Sha384::sign(&self.signing, message, &mut signature)?;
        let mut pq = [0; mldsa::SIGNATURE_LEN];
        assert!(mldsa::sign(
            &self.mldsa_secret,
            message,
            crypto::P384_MLDSA_CONTEXT,
            &[7; 32],
            &mut pq
        ));
        signature.extend_from_slice(&pq);
        Ok(signature)
    }
    fn agree(&self, peer: &[u8]) -> iron_privacy_guardian::error::Result<Zeroizing<Vec<u8>>> {
        let mut shared = Zeroizing::new(vec![0; 48]);
        EcdhP384::agree(&self.encryption, peer, &mut shared)?;
        Ok(shared)
    }
}

#[test]
fn independent_identity_and_mldsa_keygen_agree() {
    let v = fixture();
    let service = FixtureService::new(&v);
    // IronCrypto's FIPS 204 key generation from the seed matches OpenSSL's.
    let seed: [u8; 32] = bytes(&v["mldsa_seed_hex"]).try_into().unwrap();
    let (mut mldsa_public, mut secret) = (
        Box::new([0; mldsa::PUBLIC_KEY_LEN]),
        Box::new([0; mldsa::SECRET_KEY_LEN]),
    );
    assert!(mldsa::keygen(&seed, &mut mldsa_public, &mut secret));
    let (mut encryption, mut signing) = ([0; 97], vec![0; 97]);
    EcdhP384::public_key(&service.encryption, &mut encryption).unwrap();
    EcdsaP384Sha384::public_key(&service.signing, &mut signing).unwrap();
    signing.extend_from_slice(&mldsa_public[..]);
    let derived = crypto::identity(crypto::Suite::P384MlDsa, &encryption, &signing).unwrap();
    assert_eq!(derived, service.public);
    assert_eq!(derived.format, crypto::P384_MLDSA_KEY_FORMAT);
    let metadata = artifact::inspect(&serde_json::to_vec(&v["public"]).unwrap()).unwrap();
    assert_eq!(metadata.format, crypto::P384_MLDSA_KEY_FORMAT);
}

#[test]
fn independent_composite_signatures_verify_and_mu_matches_openssl() {
    let v = fixture();
    let public: PublicKey = decode(&v["public"]);
    let mldsa_public = &public.signing_key_bytes().unwrap()[97..];
    for item in v["messages"].as_array().unwrap() {
        let message = bytes(&item["message_hex"]);
        let signature: Signature = decode(&item["signature"]);
        crypto::verify(&public, &public.fingerprint, &signature, &message).unwrap();
        let framed = framed(
            "APG detached signature v1 ecdsa-p384-mldsa65",
            &[public.fingerprint.as_bytes(), &message],
        );
        let mu = crypto::mldsa_mu(mldsa_public, crypto::P384_MLDSA_CONTEXT, &framed).unwrap();
        assert_eq!(mu.to_vec(), bytes(&item["mu_hex"]));
        // Either half alone is insufficient.
        for index in [10, 96 * 2 + 10, signature.signature.len() - 2] {
            let mut forged = decode::<Signature>(&item["signature"]);
            let flipped = if &forged.signature[index..index + 1] == "0" {
                "1"
            } else {
                "0"
            };
            forged.signature.replace_range(index..index + 1, flipped);
            assert!(crypto::verify(&public, &public.fingerprint, &forged, &message).is_err());
        }
    }
    let message = bytes(&v["negative"]["message_hex"]);
    for name in ["wrong_context_signature", "high_s_signature"] {
        let forged = Signature {
            format: "apg-signature-v1".into(),
            signer: public.fingerprint.clone(),
            algorithm: crypto::P384_MLDSA.into(),
            signature: v["negative"][name].as_str().unwrap().into(),
        };
        assert_eq!(
            crypto::verify(&public, &public.fingerprint, &forged, &message)
                .unwrap_err()
                .code,
            "authentication_failed",
            "{name}"
        );
    }
}

#[test]
fn provider_signatures_self_verify_and_envelopes_use_p384() {
    let v = fixture();
    let service = FixtureService::new(&v);
    let data = b"composite provider signature";
    let signature = crypto::sign_with(&service, data).unwrap();
    assert_eq!(signature.algorithm, crypto::P384_MLDSA);
    crypto::verify(
        &service.public,
        &service.public.fingerprint,
        &signature,
        data,
    )
    .unwrap();

    // The oracle's envelope decrypts through the provider; APG encrypts with the P-384 suite.
    let envelope: Envelope = decode(&v["envelope"]);
    assert_eq!(envelope.suite, crypto::P384_SUITE);
    assert_eq!(
        &crypto::decrypt_with(&service, &envelope).unwrap()[..],
        b"PUBLIC p384-mldsa65 envelope"
    );
    let sealed = crypto::encrypt(&service.public, &service.public.fingerprint, data).unwrap();
    assert_eq!(sealed.suite, crypto::P384_SUITE);
    assert_eq!(&crypto::decrypt_with(&service, &sealed).unwrap()[..], data);
}

#[test]
fn independent_certificates_verify_and_drive_snapshots() {
    let v = fixture();
    let public: PublicKey = decode(&v["public"]);
    let fingerprint = public.fingerprint.clone();
    for (value, reason) in v["revocations"].as_array().unwrap().iter().zip([
        RevocationReason::Compromised,
        RevocationReason::Superseded,
        RevocationReason::Retired,
    ]) {
        let revocation: Revocation = decode(value);
        assert_eq!(revocation.reason, reason);
        lifecycle::verify_revocation(&public, &fingerprint, &revocation).unwrap();
    }
    let validity: Validity = decode(&v["validity"]);
    lifecycle::verify_validity(&public, &fingerprint, &validity).unwrap();
    let mut store = TrustStore::default();
    store.add(public.clone(), &fingerprint).unwrap();
    store.set_validity(validity, &fingerprint).unwrap();
    store
        .revoke(decode(&v["revocations"][2]), &fingerprint)
        .unwrap();
    assert_eq!(store.digest().unwrap().len(), 96);
}

#[test]
fn suites_cannot_be_relabeled() {
    let v = fixture();
    let public: PublicKey = decode(&v["public"]);
    let item = &v["messages"][1];
    let message = bytes(&item["message_hex"]);
    // Presenting the composite identity as plain P-384 fails its format checks.
    let mut relabeled = public.clone();
    relabeled.format = crypto::P384_KEY_FORMAT.into();
    assert!(relabeled.validate().is_err());
    // The ECDSA half alone is not an ecdsa-p384-sha384 signature for this identity.
    let composite: Signature = decode(&item["signature"]);
    let ecdsa_only = Signature {
        algorithm: crypto::ECDSA_P384.into(),
        signature: composite.signature[..192].into(),
        ..composite
    };
    assert!(crypto::verify(&public, &public.fingerprint, &ecdsa_only, &message).is_err());
}
