//! Fixed hybrid post-quantum fixtures generated by PyCA/OpenSSL
//! (tests/interop/hybrid_reference.py), not by IPG or IronCrypto.
//! All seeds and passwords in these fixtures are public test data.
use ic_core::traits::{Kdf, KeyAgreement};
use ic_ec::X25519;
use ic_mlkem::{
    MlKem768,
    kem::{CIPHERTEXT_LEN, DECAPS_KEY_LEN, ENCAPS_KEY_LEN},
};
use iron_privacy_guard::crypto::{self, Envelope, PublicKey, SecretKey, Signature};
use serde::de::DeserializeOwned;
use serde_json::Value;

fn fixture() -> Value {
    serde_json::from_str(include_str!("vectors/native-hybrid-v1.json")).unwrap()
}
fn decode<T: DeserializeOwned>(value: &Value) -> T {
    serde_json::from_value(value.clone()).unwrap()
}
fn bytes(value: &Value) -> Vec<u8> {
    hex::decode(value.as_str().unwrap()).unwrap()
}

#[test]
fn independent_hybrid_identity_unlocks_to_the_same_seeds() {
    let v = fixture();
    let secret: SecretKey = decode(&v["secret"]);
    let seeds = bytes(&v["seeds_hex"]);
    let public: PublicKey = decode(&v["public"]);
    public.validate().unwrap();
    assert_eq!(secret.public, public);
    // IronCrypto derives the same ML-KEM-768 key from the FIPS 203 seed as OpenSSL.
    let (mut ek, mut dk) = ([0; ENCAPS_KEY_LEN], [0; DECAPS_KEY_LEN]);
    MlKem768::keygen_deterministic(
        seeds[64..96].try_into().unwrap(),
        seeds[96..128].try_into().unwrap(),
        &mut ek,
        &mut dk,
    );
    assert_eq!(
        ek.to_vec(),
        public.encryption_key_bytes().unwrap()[..ENCAPS_KEY_LEN]
    );
    // And the same ML-DSA-65 key from the FIPS 204 seed.
    let (mut pk, mut sk) = (
        [0; ic_mldsa::sign::PUBLIC_KEY_LEN],
        Box::new([0; ic_mldsa::sign::SECRET_KEY_LEN]),
    );
    assert!(ic_mldsa::sign::keygen(
        seeds[128..160].try_into().unwrap(),
        &mut pk,
        &mut sk
    ));
    assert_eq!(pk.to_vec(), public.signing_key_bytes().unwrap()[32..]);
    let password = bytes(&v["password_hex"]);
    let identity = crypto::unlock_identity(&secret, &password).unwrap();
    assert_eq!(crypto::IdentityKey::public(&identity), &public);
    assert!(crypto::unlock_identity(&secret, &password[..password.len() - 1]).is_err());
    // The fixed-size v1 unlock API refuses hybrid secrets instead of truncating.
    assert!(crypto::unlock(&secret, &password).is_err());
}

#[test]
fn independent_hybrid_envelopes_decrypt_with_matching_intermediates() {
    use ic_kdf::Hkdf;
    use ic_mac::HmacSha256;
    let v = fixture();
    let secret: SecretKey = decode(&v["secret"]);
    let password = bytes(&v["password_hex"]);
    let seeds = bytes(&v["seeds_hex"]);
    let (mut ek, mut dk) = ([0; ENCAPS_KEY_LEN], [0; DECAPS_KEY_LEN]);
    MlKem768::keygen_deterministic(
        seeds[64..96].try_into().unwrap(),
        seeds[96..128].try_into().unwrap(),
        &mut ek,
        &mut dk,
    );
    for item in v["messages"].as_array().unwrap() {
        let envelope: Envelope = decode(&item["envelope"]);
        let trace = &item["encryption_trace"];
        let ephemeral = bytes(&item["envelope"]["ephemeral_key"]);
        let mut kem = [0; 32];
        MlKem768::decapsulate(
            &dk,
            ephemeral[..CIPHERTEXT_LEN].try_into().unwrap(),
            &mut kem,
        )
        .unwrap();
        assert_eq!(kem.to_vec(), bytes(&trace["kem_shared_secret_hex"]));
        let mut classical = [0; 32];
        X25519::agree(&seeds[..32], &ephemeral[CIPHERTEXT_LEN..], &mut classical).unwrap();
        assert_eq!(
            classical.to_vec(),
            bytes(&trace["x25519_shared_secret_hex"])
        );
        let mut key = [0; 32];
        Hkdf::<HmacSha256>::derive(
            &[kem, classical].concat(),
            b"IPG encryption v1",
            &bytes(&trace["aad_hex"]),
            &mut key,
        )
        .unwrap();
        assert_eq!(key.to_vec(), bytes(&trace["derived_key_hex"]));
        assert_eq!(
            *crypto::decrypt(&secret, &password, &envelope).unwrap(),
            bytes(&item["message_hex"])
        );
    }
}

#[test]
fn every_hybrid_component_is_authenticated() {
    let v = fixture();
    let secret: SecretKey = decode(&v["secret"]);
    let password = bytes(&v["password_hex"]);
    let item = &v["messages"][5];
    // Byte offsets inside the ML-KEM ciphertext and inside the X25519 key.
    for offset in [
        0,
        CIPHERTEXT_LEN / 2,
        CIPHERTEXT_LEN - 1,
        CIPHERTEXT_LEN + 5,
    ] {
        let mut ephemeral = bytes(&item["envelope"]["ephemeral_key"]);
        ephemeral[offset] ^= 1;
        let mut tampered = item["envelope"].clone();
        tampered["ephemeral_key"] = Value::String(hex::encode(ephemeral));
        let tampered: Envelope = decode(&tampered);
        assert!(
            crypto::decrypt(&secret, &password, &tampered).is_err(),
            "{offset}"
        );
    }
    for field in ["tag", "nonce", "ciphertext"] {
        let mut tampered = item["envelope"].clone();
        let mut decoded = bytes(&tampered[field]);
        decoded[0] ^= 1;
        tampered[field] = Value::String(hex::encode(decoded));
        assert!(crypto::decrypt(&secret, &password, &decode(&tampered)).is_err());
    }
    let mut downgraded = item["envelope"].clone();
    downgraded["suite"] = crypto::SUITE.into();
    assert!(decode::<Envelope>(&downgraded).validate().is_err());
}

#[test]
fn independent_composite_signatures_verify() {
    let v = fixture();
    let secret: SecretKey = decode(&v["secret"]);
    let password = bytes(&v["password_hex"]);
    for item in v["messages"].as_array().unwrap() {
        let message = bytes(&item["message_hex"]);
        let signature: Signature = decode(&item["signature"]);
        assert_eq!(signature.algorithm, crypto::COMPOSITE);
        crypto::verify(
            &secret.public,
            &secret.public.fingerprint,
            &signature,
            &message,
        )
        .unwrap();
        // Ed25519 is deterministic; ML-DSA is hedged, so only its half differs.
        let reproduced = crypto::sign(&secret, &password, &message).unwrap();
        assert_eq!(reproduced.signature[..128], signature.signature[..128]);
        crypto::verify(
            &secret.public,
            &secret.public.fingerprint,
            &reproduced,
            &message,
        )
        .unwrap();
        let mut altered = message.clone();
        altered.push(0);
        assert!(
            crypto::verify(
                &secret.public,
                &secret.public.fingerprint,
                &signature,
                &altered
            )
            .is_err()
        );
    }
    let revocation: iron_privacy_guard::lifecycle::Revocation = decode(&v["revocation"]);
    iron_privacy_guard::lifecycle::verify_revocation(
        &secret.public,
        &secret.public.fingerprint,
        &revocation,
    )
    .unwrap();
    let validity: iron_privacy_guard::lifecycle::Validity = decode(&v["validity"]);
    iron_privacy_guard::lifecycle::verify_validity(
        &secret.public,
        &secret.public.fingerprint,
        &validity,
    )
    .unwrap();
    // A snapshot holding the hybrid identity with both certificates stays in bounds.
    let mut store = iron_privacy_guard::trust::TrustStore::default();
    store
        .add(secret.public.clone(), &secret.public.fingerprint)
        .unwrap();
    store
        .set_validity(validity, &secret.public.fingerprint)
        .unwrap();
    store
        .revoke(revocation, &secret.public.fingerprint)
        .unwrap();
    let size = serde_json::to_vec_pretty(&store).unwrap().len() as u64;
    assert!(
        size * iron_privacy_guard::trust::MAX_IDENTITIES as u64
            <= iron_privacy_guard::trust::MAX_STORE_BYTES,
        "{size}"
    );
}

#[test]
fn hybrid_artifacts_inspect_without_secrets() {
    let v = fixture();
    for name in ["public", "secret"] {
        let metadata =
            iron_privacy_guard::artifact::inspect(&serde_json::to_vec(&v[name]).unwrap()).unwrap();
        assert_eq!(metadata.fingerprint.unwrap(), v["public"]["fingerprint"]);
    }
    let mut truncated = v["secret"].clone();
    truncated["ciphertext"] =
        Value::String(v["secret"]["ciphertext"].as_str().unwrap()[..128].into());
    assert!(
        iron_privacy_guard::artifact::inspect(&serde_json::to_vec(&truncated).unwrap()).is_err()
    );
}
