//! Shared machine-readable constraints; semantic authentication remains at runtime.
use ipg_json::{Schema, SchemaGenerator, json_schema};

macro_rules! fixed {
    ($name:ident, $value:expr) => {
        pub fn $name(_: &mut SchemaGenerator) -> Schema {
            json_schema!({"type":"string", "const":$value})
        }
    };
}
fixed!(protocol, "ipg/1");
fixed!(envelope_format, "ipg-envelope-v1");
fixed!(signature_format, "ipg-signature-v1");
fixed!(revocation_format, "ipg-revocation-v1");
fixed!(validity_format, "ipg-validity-v1");
fixed!(hardware_key_format, crate::provider::HARDWARE_KEY_FORMAT);
fixed!(tpm_key_format, crate::provider::TPM_KEY_FORMAT);
pub fn tpm_parent(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "enum":[crate::provider::TPM_PARENT, crate::provider::WINDOWS_TPM_PARENT],
        "description":"IPG's owner-hierarchy P-384 storage root (Linux) or the Windows storage root key at 0x81000001."})
}
fixed!(kms_key_format, crate::provider::KMS_KEY_FORMAT);
fixed!(cng_key_format, crate::provider::CNG_KEY_FORMAT);
fixed!(cng_provider, crate::provider::CNG_PROVIDER);
/// Generated CNG key names: `ipg-<32 hex>-enc` for the ECDH key.
pub fn cng_encryption_key_name(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "minLength":40, "maxLength":40,
        "pattern":"^ipg-[0-9a-f]{32}-enc$"})
}
/// Generated CNG key names: `ipg-<32 hex>-sig` for the ECDSA key.
pub fn cng_signing_key_name(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "minLength":40, "maxLength":40,
        "pattern":"^ipg-[0-9a-f]{32}-sig$"})
}

pub fn aws_region(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "minLength":1, "maxLength":32, "pattern":"^[a-z0-9-]+$", "not":{"pattern":"[^a-z0-9-]"}})
}
/// A KMS key ARN; aliases are refused because they can be repointed.
pub fn optional_kms_key_arn(generator: &mut SchemaGenerator) -> Schema {
    let mut schema = kms_key_arn(generator);
    schema.insert("type".into(), ipg_json::json!(["string", "null"]));
    schema
}
pub fn kms_key_arn(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "maxLength":160,
        "pattern":"^arn:(aws|aws-us-gov|aws-cn|aws-iso|aws-iso-b):kms:[a-z0-9-]{1,32}:[0-9]{12}:key/[A-Za-z0-9-]{1,64}$", "not":{"pattern":"[^A-Za-z0-9:/-]"}})
}
fixed!(kdf, "argon2id-m65536-t3-p4");
fixed!(openpgp_key_format, crate::openpgp::KEY_FORMAT);
fixed!(evidence_format, "ipg-tpm-evidence-v1");
fixed!(challenge_format, "ipg-tpm-challenge-v1");
fixed!(challenge_secret_format, "ipg-tpm-challenge-secret-v1");
fixed!(response_format, "ipg-tpm-response-v1");
fixed!(stream_format, crate::stream::FORMAT);
fixed!(stream_signature_format, crate::stream_signature::FORMAT);
fixed!(sha384_algorithm, "sha2-384");
pub fn stream_signature_bytes(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"integer", "minimum":0, "maximum":u64::MAX})
}
pub fn stream_chunk_size(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"integer", "const":crate::stream::CHUNK_SIZE})
}
/// A marshalled TPM structure (public area, attestation, signature or credential
/// blob) as lowercase hex, 1..1024 bytes.
pub fn tpm_structure(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "minLength":2, "maxLength":2048,
        "pattern":"^([0-9a-f]{2})+$", "not":{"pattern":"[^0-9a-f]"}})
}
/// DER certificates as lowercase hex: the EK certificate, then platform-supplied intermediates.
pub fn ek_certificates(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"array", "minItems":1, "maxItems":4, "items":{"type":"string", "minLength":2,
        "maxLength":8192, "pattern":"^([0-9a-f]{2})+$", "not":{"pattern":"[^0-9a-f]"}}})
}
/// A pinned v4 or v6 OpenPGP fingerprint; either case, since GnuPG prints uppercase.
pub fn openpgp_fingerprint(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "minLength":40, "maxLength":64,
        "pattern":"^([0-9A-Fa-f]{40}|[0-9A-Fa-f]{64})$", "not":{"pattern":"[^0-9A-Fa-f]"},
        "description":"OpenPGP primary-key fingerprint: v4 40 hex or v6 64 hex characters, no spaces."})
}
/// An OpenPGP fingerprint as IPG reports it.
pub fn openpgp_key_fingerprint(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "minLength":40, "maxLength":64,
        "pattern":"^([0-9a-f]{40}|[0-9a-f]{64})$", "not":{"pattern":"[^0-9a-f]"}})
}
pub fn openpgp_user_id(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "minLength":1, "maxLength":crate::openpgp::MAX_USER_ID_BYTES,
        "pattern":"^[^\\u0000-\\u001f\\u007f-\\u009f]+$",
        "description":"1..256 bytes of UTF-8 without control characters (byte length checked at runtime)."})
}
/// A binary OpenPGP certificate generated by IPG, as lowercase hex.
pub fn openpgp_certificate_hex(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "minLength":2, "maxLength":crate::openpgp::MAX_OWN_CERTIFICATE_BYTES * 2,
        "pattern":"^([0-9a-f]{2})+$", "not":{"pattern":"[^0-9a-f]"}})
}
/// A sealed binary OpenPGP secret key, as lowercase hex.
pub fn openpgp_secret_hex(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "minLength":2, "maxLength":crate::openpgp::MAX_SECRET_BYTES * 2,
        "pattern":"^([0-9a-f]{2})+$", "not":{"pattern":"[^0-9a-f]"}})
}
fixed!(scope, "entire-identity");

use crate::crypto::{
    COMPOSITE, ECDSA_P384, ED25519, HYBRID_KEY_FORMAT, HYBRID_SECRET_FORMAT, HYBRID_SUITE,
    KEY_FORMAT, P384_KEY_FORMAT, P384_MLDSA, P384_MLDSA_KEY_FORMAT, P384_SUITE, SECRET_FORMAT,
    SUITE,
};
const CURVE25519_KEY: &str = "^[0-9a-f]{64}$";
const P384_KEY: &str = "^04[0-9a-f]{192}$";
/// ML-KEM-768 encapsulation key (1184 bytes) followed by an X25519 key.
const HYBRID_KEY: &str = "^[0-9a-f]{2432}$";
/// Ed25519 key followed by an ML-DSA-65 key (1952 bytes).
const HYBRID_SIGNING_KEY: &str = "^[0-9a-f]{3968}$";
/// Ed25519 signature followed by an ML-DSA-65 signature (3309 bytes).
const COMPOSITE_SIGNATURE: &str = "^[0-9a-f]{6746}$";
/// Uncompressed P-384 point followed by an ML-DSA-65 key (1952 bytes).
const P384_MLDSA_SIGNING_KEY: &str = "^04[0-9a-f]{4096}$";
/// Fixed-width low-s ECDSA P-384 r||s followed by an ML-DSA-65 signature.
const P384_MLDSA_SIGNATURE: &str = "^[0-9a-f]{6810}$";
/// ML-KEM-768 ciphertext (1088 bytes) followed by an X25519 ephemeral key.
const HYBRID_EPHEMERAL: &str = "^[0-9a-f]{2240}$";

/// SHA-256 (ipg-public-v1) or SHA-384 (P-384 and hybrid) identity fingerprint.
pub fn fingerprint(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "minLength":64, "maxLength":96,
        "pattern":"^([0-9a-f]{64}|[0-9a-f]{96})$", "not":{"pattern":"[^0-9a-f]"},
        "description":"64 hex characters for ipg-public-v1 identities, 96 for P-384, P-384 plus ML-DSA and hybrid identities."})
}
const FINGERPRINT_256: &str = "^[0-9a-f]{64}$";
const FINGERPRINT_384: &str = "^[0-9a-f]{96}$";

pub fn public_format(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "enum":[KEY_FORMAT, P384_KEY_FORMAT, HYBRID_KEY_FORMAT, P384_MLDSA_KEY_FORMAT]})
}
pub fn secret_format(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "enum":[SECRET_FORMAT, HYBRID_SECRET_FORMAT]})
}
/// 32-byte Curve25519 keys, 97-byte uncompressed SEC1 P-384 points, or hybrid
/// ML-KEM-768 plus X25519 encryption and Ed25519 plus ML-DSA-65 signing keys.
pub fn public_key_bytes(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "minLength":64, "maxLength":4098,
        "pattern":"^([0-9a-f]{64}|04[0-9a-f]{192}|[0-9a-f]{2432}|[0-9a-f]{3968}|04[0-9a-f]{4096})$", "not":{"pattern":"[^0-9a-f]"},
        "description":"Length and encoding follow the artifact suite; P-384 points must lie on the curve and ML-KEM keys must be canonical (checked at runtime)."})
}
pub fn ephemeral_bytes(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "minLength":64, "maxLength":2240,
        "pattern":"^([0-9a-f]{64}|04[0-9a-f]{192}|[0-9a-f]{2240})$", "not":{"pattern":"[^0-9a-f]"},
        "description":"Sender ephemeral public key in the envelope suite; hybrid envelopes prefix the ML-KEM-768 ciphertext."})
}
/// Protected seeds: 64 bytes for ipg-secret-v1, 160 for ipg-secret-hybrid-v1.
pub fn seed_ciphertext(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "minLength":128, "maxLength":320,
        "pattern":"^([0-9a-f]{128}|[0-9a-f]{320})$", "not":{"pattern":"[^0-9a-f]"}})
}
/// Software secret keys bind the Curve25519 or hybrid identity suites.
pub fn software_public_key(_: &mut SchemaGenerator) -> Schema {
    let identity = |format: &str, encryption: &str, signing: &str, fingerprint: &str| {
        ipg_json::json!({"type":"object", "additionalProperties":false,
            "required":["format","encryption_key","signing_key","fingerprint"],
            "properties":{"format":{"type":"string","const":format},
                "encryption_key":{"type":"string","pattern":encryption,"not":{"pattern":"[^0-9a-f]"}},
                "signing_key":{"type":"string","pattern":signing,"not":{"pattern":"[^0-9a-f]"}},
                "fingerprint":{"type":"string","pattern":fingerprint,"not":{"pattern":"[^0-9a-f]"}}}})
    };
    json_schema!({"oneOf":[identity(KEY_FORMAT, CURVE25519_KEY, CURVE25519_KEY, FINGERPRINT_256),
        identity(HYBRID_KEY_FORMAT, HYBRID_KEY, HYBRID_SIGNING_KEY, FINGERPRINT_384)]})
}
fn pattern(value: &str) -> ipg_json::Value {
    ipg_json::json!({"pattern":value})
}
fn when(field: &str, value: &str, then: ipg_json::Value) -> ipg_json::Value {
    ipg_json::json!({"if":{"properties":{field:{"const":value}}}, "then":{"properties":then}})
}
pub fn public_suite(schema: &mut Schema) {
    schema.insert(
        "allOf".into(),
        ipg_json::json!([
            when("format", KEY_FORMAT, ipg_json::json!({"encryption_key":pattern(CURVE25519_KEY),"signing_key":pattern(CURVE25519_KEY),"fingerprint":pattern(FINGERPRINT_256)})),
            when("format", P384_KEY_FORMAT, ipg_json::json!({"encryption_key":pattern(P384_KEY),"signing_key":pattern(P384_KEY),"fingerprint":pattern(FINGERPRINT_384)})),
            when("format", HYBRID_KEY_FORMAT, ipg_json::json!({"encryption_key":pattern(HYBRID_KEY),"signing_key":pattern(HYBRID_SIGNING_KEY),"fingerprint":pattern(FINGERPRINT_384)})),
            when("format", P384_MLDSA_KEY_FORMAT, ipg_json::json!({"encryption_key":pattern(P384_KEY),"signing_key":pattern(P384_MLDSA_SIGNING_KEY),"fingerprint":pattern(FINGERPRINT_384)})),
        ]),
    );
}
/// Each secret format binds its own identity suite and seed length.
pub fn secret_suite(schema: &mut Schema) {
    schema.insert(
        "allOf".into(),
        ipg_json::json!([
            when("format", SECRET_FORMAT, ipg_json::json!({"public":{"properties":{"format":{"const":KEY_FORMAT}}},"ciphertext":pattern("^[0-9a-f]{128}$")})),
            when("format", HYBRID_SECRET_FORMAT, ipg_json::json!({"public":{"properties":{"format":{"const":HYBRID_KEY_FORMAT}}},"ciphertext":pattern("^[0-9a-f]{320}$")})),
        ]),
    );
}
pub fn suite(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "enum":[SUITE, P384_SUITE, HYBRID_SUITE]})
}
pub fn envelope_suite(schema: &mut Schema) {
    schema.insert(
        "allOf".into(),
        ipg_json::json!([
            when(
                "suite",
                SUITE,
                ipg_json::json!({"ephemeral_key":pattern(CURVE25519_KEY)})
            ),
            when(
                "suite",
                P384_SUITE,
                ipg_json::json!({"ephemeral_key":pattern(P384_KEY)})
            ),
            when(
                "suite",
                HYBRID_SUITE,
                ipg_json::json!({"ephemeral_key":pattern(HYBRID_EPHEMERAL)})
            ),
        ]),
    );
}
pub fn signature_algorithm(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "enum":[ED25519, ECDSA_P384, COMPOSITE, P384_MLDSA],
        "description":"Must be the signer identity suite's algorithm (checked at runtime)."})
}
/// 64-byte Ed25519, 96-byte fixed-width low-s ECDSA P-384 r||s, 3373-byte composite
/// Ed25519 plus ML-DSA-65, or 3405-byte composite ECDSA P-384 plus ML-DSA-65 signatures.
pub fn signature_bytes(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "minLength":128, "maxLength":6810,
        "pattern":"^([0-9a-f]{128}|[0-9a-f]{192}|[0-9a-f]{6746}|[0-9a-f]{6810})$", "not":{"pattern":"[^0-9a-f]"}})
}
pub fn signature_suite(schema: &mut Schema) {
    schema.insert(
        "allOf".into(),
        ipg_json::json!([
            when(
                "algorithm",
                ED25519,
                ipg_json::json!({"signature":pattern("^[0-9a-f]{128}$")})
            ),
            when(
                "algorithm",
                ECDSA_P384,
                ipg_json::json!({"signature":pattern("^[0-9a-f]{192}$")})
            ),
            when(
                "algorithm",
                COMPOSITE,
                ipg_json::json!({"signature":pattern(COMPOSITE_SIGNATURE)})
            ),
            when(
                "algorithm",
                P384_MLDSA,
                ipg_json::json!({"signature":pattern(P384_MLDSA_SIGNATURE)})
            ),
        ]),
    );
}
/// PKCS#11 CKA_ID values. Generated IDs use 16 random bytes.
pub fn key_id(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "minLength":2, "maxLength":128, "pattern":"^([0-9a-f]{2}){1,64}$", "not":{"pattern":"[^0-9a-f]"}})
}
/// A PKCS#11 token-information text field, blank padding removed.
pub fn token_text<const N: usize>(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "maxLength":N})
}
pub fn token_serial(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "minLength":1, "maxLength":16,
        "description":"PKCS#11 token serial number exactly as reported by hardware.tokens"})
}
pub fn key_label(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "minLength":1, "maxLength":64,
        "description":"CKA_LABEL for both generated key pairs; informational, never used for lookup"})
}

pub fn hex_bytes<const N: usize>(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "minLength":N*2, "maxLength":N*2,
        "pattern":format!("^[0-9a-f]{{{}}}$", N*2)})
}
/// An MLS hash reference: `Nh` bytes, 32 for suites 1 and 3 or 48 for suite 7.
pub fn mls_reference(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "pattern":"^([0-9a-f]{64}|[0-9a-f]{96})$"})
}
pub fn ciphertext(_: &mut SchemaGenerator) -> Schema {
    // Runtime accepts either hex case only for variable-length ciphertext.
    json_schema!({"type":"string", "pattern":"^([0-9a-fA-F]{2})*$",
        "not":{"pattern":"[^0-9a-fA-F]"}})
}
pub fn unix_time(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"integer", "minimum":0, "maximum":crate::lifecycle::MAX_UNIX_TIME})
}
pub fn time_start(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"integer", "minimum":0, "maximum":crate::lifecycle::MAX_UNIX_TIME-1,
        "description":"Unix seconds, inclusive; must be strictly less than not_after (checked at runtime)."})
}
pub fn time_end(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"integer", "minimum":1, "maximum":crate::lifecycle::MAX_UNIX_TIME,
        "description":"Unix seconds, exclusive; must be strictly greater than not_before (checked at runtime)."})
}
fixed!(grant_format, crate::delegation::FORMAT);
fixed!(message_format, crate::message::FORMAT);
fixed!(json_signature_format, crate::json_signature::FORMAT);
fixed!(approval_format, crate::approval::FORMAT);
fixed!(rotation_format, crate::rotation::FORMAT);
fixed!(share_format, crate::backup::FORMAT);
fixed!(mls_key_package_format, crate::mls_ops::KEY_PACKAGE_FORMAT);
pub fn mls_sealed_format(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "enum":[crate::mls_ops::STATE_FORMAT, crate::mls_ops::KEY_PACKAGE_SECRETS_FORMAT]})
}
pub fn mls_lifetime(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"integer", "minimum":1, "maximum":crate::mls_ops::MAX_LIFETIME,
        "description":"Seconds the KeyPackage stays valid (at most 90 days)."})
}
pub fn mls_adds(generator: &mut SchemaGenerator) -> Schema {
    let item = generator.subschema_for::<crate::mls_ops::MlsAdd>();
    json_schema!({"type":"array", "maxItems":crate::mls_ops::MAX_MEMBERS_PER_COMMIT, "items":item})
}
pub fn mls_removes(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"array", "maxItems":crate::mls_ops::MAX_MEMBERS_PER_COMMIT,
        "items":{"type":"string", "pattern":"^([0-9a-f]{64}|[0-9a-f]{96})$"},
        "description":"IPG fingerprints of members to remove."})
}
pub fn mls_export_length(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"integer", "minimum":1, "maximum":64})
}
pub fn mls_label(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "minLength":1, "maxLength":255})
}
pub fn share_threshold(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"integer", "minimum":2, "maximum":crate::backup::MAX_SHARES,
        "description":"Shares needed to recover (k); at most the number of shares (checked at runtime)."})
}
pub fn share_outputs(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"array", "minItems":2, "maxItems":crate::backup::MAX_SHARES,
        "items":{"type":"string"}, "description":"One output path per share (n); hand each to a different custodian."})
}
pub fn share_inputs(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"array", "minItems":2, "maxItems":crate::backup::MAX_SHARES,
        "items":{"type":"string"}, "description":"ipg-share-v1 files of one backup, at least its threshold."})
}
pub fn rotation_chain(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"array", "minItems":1, "maxItems":crate::rotation::MAX_CHAIN,
        "items":{"type":"string"}, "description":"ipg-rotation-v1 files in order, starting from the pinned identity."})
}
fixed!(audit_format, crate::audit::FORMAT);
fixed!(audit_checkpoint_format, crate::audit::CHECKPOINT_FORMAT);
pub fn audit_event(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"object", "description":"Caller-supplied JSON object, at most 64 KiB in canonical form."})
}
pub fn checkpoint_files(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"array", "maxItems":crate::audit::MAX_CHECKPOINTS,
        "items":{"type":"string"}, "description":"ipg-audit-checkpoint-v1 files to check against the log."})
}
pub fn approval_lifetime(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"integer", "minimum":1, "maximum":crate::approval::MAX_LIFETIME,
        "description":"Seconds from the host clock until the approval expires (at most 7 days)."})
}
pub fn approvers(generator: &mut SchemaGenerator) -> Schema {
    let item = generator.subschema_for::<crate::Approver>();
    json_schema!({"type":"array", "minItems":1, "maxItems":crate::approval::MAX_APPROVERS, "items":item,
        "description":"The pinned approver set (n); fingerprints must be distinct."})
}
pub fn approval_files(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"array", "minItems":1, "maxItems":crate::approval::MAX_APPROVALS,
        "items":{"type":"string"}, "description":"ipg-approval-v1 files; order does not matter."})
}
pub fn threshold(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"integer", "minimum":1, "maximum":crate::approval::MAX_APPROVERS,
        "description":"Distinct valid approvals required (m); at most the number of approvers (checked at runtime)."})
}
fixed!(canonicalization, crate::json_signature::CANONICALIZATION);
fixed!(intoto_payload_type, crate::provenance::PAYLOAD_TYPE);
pub fn base64_text(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "pattern":"^[A-Za-z0-9+/]*={0,2}$", "contentEncoding":"base64"})
}
pub fn dsse_signatures(generator: &mut SchemaGenerator) -> Schema {
    let item = generator.subschema_for::<crate::provenance::EnvelopeSignature>();
    json_schema!({"type":"array", "minItems":1, "maxItems":crate::provenance::MAX_SIGNATURES, "items":item})
}
pub fn provenance_action(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "minLength":1, "maxLength":crate::provenance::MAX_ACTION_BYTES,
        "pattern":"^[A-Za-z0-9._:/-]+$", "description":"Declared action, such as build, deploy or review."})
}
pub fn optional_provenance_action(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":["string","null"], "minLength":1, "maxLength":crate::provenance::MAX_ACTION_BYTES,
        "pattern":"^[A-Za-z0-9._:/-]+$"})
}
pub fn artifact_name(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "minLength":1, "maxLength":crate::provenance::MAX_NAME_BYTES,
        "pattern":"^[^\\u0000-\\u001f\\u007f-\\u009f]+$", "description":"Name recorded in the statement; unique within subjects or materials."})
}
pub fn provenance_subjects(generator: &mut SchemaGenerator) -> Schema {
    let item = generator.subschema_for::<crate::ProvenanceArtifact>();
    json_schema!({"type":"array", "minItems":1, "maxItems":crate::provenance::MAX_ARTIFACTS, "items":item})
}
pub fn provenance_materials(generator: &mut SchemaGenerator) -> Schema {
    let item = generator.subschema_for::<crate::ProvenanceArtifact>();
    json_schema!({"type":"array", "maxItems":crate::provenance::MAX_ARTIFACTS, "items":item})
}
pub fn message_lifetime(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"integer", "minimum":1, "maximum":crate::message::MAX_LIFETIME,
        "description":"Seconds from the host clock until the message expires."})
}
pub fn conversation(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":["string","null"], "minLength":1, "maxLength":crate::message::MAX_CONVERSATION_BYTES,
        "pattern":"^[A-Za-z0-9._:/-]+$", "description":"Optional conversation label bound into the signed header."})
}
pub fn channel_binding(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":["string","null"], "minLength":32, "maxLength":crate::message::MAX_CHANNEL_BINDING*2,
        "pattern":"^([0-9a-f]{2})+$", "description":"Optional 16..64-byte channel binding, such as a TLS exporter value; the recipient must present the same value."})
}
/// Sorted, unique delegable operations (checked at runtime).
pub fn grant_operations(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"array", "minItems":1, "maxItems":crate::delegation::DELEGABLE.len(),
        "uniqueItems":true, "items":{"type":"string", "enum":crate::delegation::DELEGABLE},
        "description":"Operations the subject may perform; sorted, and a subset of the parent link's."})
}
/// Application purpose labels; empty means no purpose restriction.
pub fn grant_purposes(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"array", "maxItems":crate::delegation::MAX_PURPOSES, "uniqueItems":true,
        "items":{"type":"string", "minLength":1, "maxLength":crate::delegation::MAX_PURPOSE_BYTES,
            "pattern":"^[a-z0-9._:/-]+$"},
        "description":"Sorted application-defined purposes; empty places no purpose restriction. A child of a restricted link must restrict to a subset."})
}
pub fn grant_depth(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"integer", "minimum":0, "maximum":crate::delegation::MAX_DEPTH,
        "description":"Further re-delegations allowed; each child link must be strictly lower."})
}
pub fn grant_links(generator: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"array", "minItems":1, "maxItems":crate::delegation::MAX_LINKS,
        "items":generator.subschema_for::<crate::delegation::Link>(),
        "description":"Delegation links from the root principal to the acting identity."})
}
pub fn optional_fingerprint(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":["string","null"], "minLength":64, "maxLength":96,
        "pattern":"^([0-9a-f]{64}|[0-9a-f]{96})$"})
}
pub fn optional_grant_operation(_: &mut SchemaGenerator) -> Schema {
    let mut values: Vec<ipg_json::Value> = crate::delegation::DELEGABLE
        .iter()
        .map(|v| ipg_json::json!(v))
        .collect();
    values.push(ipg_json::Value::Null);
    json_schema!({"type":["string","null"], "enum":values})
}
pub fn optional_grant_purpose(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":["string","null"], "minLength":1, "maxLength":crate::delegation::MAX_PURPOSE_BYTES,
        "pattern":"^[a-z0-9._:/-]+$"})
}
pub fn trust_format(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "enum":["ipg-trust-v1", "ipg-trust-v2", "ipg-trust-v3"],
        "description":"IPG writes ipg-trust-v3; v1 and v2 snapshots remain readable."})
}
pub fn trust_digest(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "minLength":64, "maxLength":96,
        "pattern":"^([0-9a-f]{64}|[0-9a-f]{96})$", "not":{"pattern":"[^0-9a-f]"},
        "description":"SHA-384 snapshot digest (96 hex) for ipg-trust-v3; SHA-256 (64 hex) for v1 and v2."})
}
pub fn entries(generator: &mut SchemaGenerator) -> Schema {
    let item = generator.subschema_for::<crate::trust::TrustEntry>();
    json_schema!({"type":"array", "maxItems":crate::trust::MAX_IDENTITIES, "items":item,
        "description":"Fingerprints must be unique; every embedded certificate is authenticated at runtime."})
}
pub fn trust_version(schema: &mut Schema) {
    schema.insert(
        "allOf".into(),
        ipg_json::json!([{
            "if":{"properties":{"format":{"const":"ipg-trust-v1"}}},
            "then":{"properties":{"entries":{"items":{"properties":{"validity":{"type":"null"}}}}}}
        }]),
    );
}
/// A marshalled TPM2B structure, 1..2048 bytes of lowercase hex.
pub fn tpm_blob(_: &mut SchemaGenerator) -> Schema {
    json_schema!({"type":"string", "minLength":2, "maxLength":4096, "pattern":"^([0-9a-f]{2})+$", "not":{"pattern":"[^0-9a-f]"}})
}
